apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-delta-1
  namespace: spark-jobs
spec:
  type: Scala
  mode: cluster
  image: "my-emr-test:1.0"
  imagePullPolicy: IfNotPresent
  mainClass: org.example.DataPrep
  mainApplicationFile: "local:///home/hadoop/jars/my-spark-test.jar"
  sparkVersion: "3.5.1"
  sparkUIOptions:
    serviceLabels:
      test-label/v1: 'true'
  restartPolicy:
    type: Never
  volumes:
    - name: "spark-events-dir"
      persistentVolumeClaim:
        claimName: spark-pvc-events
  sparkConf:
    spark.eventLog.enabled: "true"

  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.5.1
    serviceAccount: sc-spark
    envFrom:
      - configMapRef:
          name: spark-run-cm
      - secretRef:
          name: spark-run-secret

  executor:
    cores: 2
    instances: 1
    memory: "1024m"
    labels:
      version: 3.5.1
    serviceAccount: sc-spark
    envFrom:
      - configMapRef:
          name: spark-run-cm
      - secretRef:
          name: spark-run-secret
