apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-pvc-scratch
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-pvc-events
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
